fix(ts/fullStory): use mockFullStoryEvent to address new babel rules issues
When working on https://github.com/mbta/skate/pull/2220, I needed to add [new babel rules to make typescript work in storybookjs](https://github.com/mbta/skate/blob/kf/asn/storybook/assets/babel.config.js#L4).
This seems to have made babel more strict and due to these rules, CI started to throw the following error:
```
tests/helpers/fullStory.test.ts(13,5): error TS2322: Type '{ identify: Mock<UnknownFunction>; event: Mock<UnknownFunction>; }' is not assignable to type '{ identify(uid: string, opts: { displayName?: string | undefined; email?: string | undefined; }): void; event(event: string, properties?: object | undefined): void; } & typeof FS'.
  Type '{ identify: Mock<UnknownFunction>; event: Mock<UnknownFunction>; }' is missing the following properties from type 'typeof FS': lookupPath, getPath, isFile, isDir, and 51 more.
tests/helpers/fullStory.test.ts(24,5): error TS2322: Type '{ identify: Mock<UnknownFunction>; event: Mock<UnknownFunction>; }' is not assignable to type '{ identify(uid: string, opts: { displayName?: string | undefined; email?: string | undefined; }): void; event(event: string, properties?: object | undefined): void; } & typeof FS'.
  Type '{ identify: Mock<UnknownFunction>; event: Mock<UnknownFunction>; }' is missing the following properties from type 'typeof FS': lookupPath, getPath, isFile, isDir, and 51 more.
```

We don't seem to get these rules applied to our `mockFullStoryEvent` helper so I've decided to convert this test over to using that helper.
I'm not sure this is the best way to address this, so I'm open to any other ideas.

---

Asana Ticket: app.asana.com/0/1148853526253420/1205339217615967/f